# Generated by Django 4.1.7 on 2025-01-27 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteSettings',
        ),
    ]
